apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ${NAMESPACE}
  labels:
    app: web
    app.kubernetes.io/part-of: ckne-hands-on
    ckne.openai.com/lab-id: "${TASK_ID}"
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
